server:
  port: 8051

spring:
  application:
    name: clickbusservice
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:postgresql://192.168.99.100:5432/clickbusdb
#    password: postgres
#    username: postgres
    url: jdbc:h2:mem:clickbusdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    generate-ddl: true
    show-sql: true
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp: 
          use_jdbc_metadata_defaults: false 

mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:mybatis/mapper/*.xml

api: