server:
  port: 8051
spring: 
  profiles:
    active:
    - dev
  application:
    name: clickbusservice
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:mybatis/mapper/*.xml
api: